### PR TITLE
A new "route" method for Readable

### PR DESCRIPTION
**Pull request by emedvedev**
A method to return a request path without executing the request. Needed for icons.

### CODE REVIEW

**Comment by enykeev** [comment]
I suggest we follow the convention and make it a separate mixin. Also, tests would be good too.

**Comment by emedvedev** [comment]
@enykeev My logic was that it belongs as a part of "Readable" because it follows the `get` method and so `route` only makes sense if we have `get`, thus the same mixin. Thoughts?

**Comment by enykeev** [comment]
The URL would be the same for any method within endpoint. One method per mixin is also more predictable, easier to reuse and test.

**Comment by emedvedev** [comment]
Got it. Will do :)

**Comment by emedvedev** [comment]
@enykeev Made a separate mixin and added tests to compare with pre-defined routes.

**Comment by enykeev** [comment]
:+1:

**Pull request merged**
