### PR TITLE
Replace http-browserify with axios

### PR DESCRIPTION
**Pull request by enykeev**

### CODE REVIEW

**Comment by Kami** [comment]
Just curious - what was the reason to switch to this library?

**Comment by enykeev** [comment]
Basically, `http-browserify` is poorly written browser drop-in replacement for node `http` module.

It pulls with it a number of other replacement modules for things like buffers and streams not required in browser environment outside supporting compatibility with original `http` module.

It lacks certain important properties of original module requiring us to hack around them or fork (which we actually did). Also, browser environment has its own specifics (CORS) that are not implemented in original module and has only minimal support in `http-browserify`. This is the reason we can't distinguish between CORS error and an absence of connection on st2web side. 

But any of this problems could have been solved if only https://github.com/substack started merging PR's. This is the last commit in the repo https://github.com/substack/http-browserify/commit/17b2990010ebd39461d1117c1e2c50c25eab869f.

**Comment by Kami** [comment]
Thanks for the clarification - I'm all for using more supported and maintained library.

**Comment by emedvedev** [comment]
LGTM. Axios is nice.

**Comment by alex-shnayder** [comment]
@enykeev Have you compared `axios` to `superagent`? I've seen many positive comments about `superagent`, but haven't had a chance to use it. Never heard about `axios`, though. Just curious if `axios` is the modern HTTP client of choice.

**Comment by enykeev** [comment]
@alex-shnayder I definitely tried it, although I don't remember any specifics.

One thing I can say for sure is that superagent has only basic support of promises (it isn't even a promise, literally `then`able https://github.com/visionmedia/superagent/blob/1822e9ffbeb6e17b67465bebc1e47b59b2037783/lib/node/index.js#L1034, don't even have `catch`) while axios always return proper promise (though the version we use treats promise as a part of the language so assume nodejs>=0.11).

Dunno about "the modern HTTP client of choice", there might be better ones, but it looks damn solid to me.

**Pull request merged**
